### ISSUE TITLE
[WinError 5] Access Denied

### ISSUE THREAD

**Issue by Fytcher** [K4YT3X/video2x#42] opened 2019-03-01 01:18 UTC
I ran into an issue. Issues appears if either cudNN or gpu mode is used.
Using a GTX 1070 with CUDA 10.1 installed and cudNN library.

The entire log:

```
              Video2X Video Enlarger

                   Version 2.4.3

[!] WARNING: Each waifu2x-caffe thread will require up to 2.5 GB of system memory
[!] WARNING: You demanded 5 threads to be created, but you only have 9.2927 GB system memory available
[!] WARNING: 12.5 GB of system memory is recommended for 5 threads
[!] WARNING: With your current amount of system memory available, 3 threads is recommended
[?] USER: Change to the recommended value? [Y/n]: Y
[!] WARNING: Each waifu2x-caffe thread will require up to 2.5 GB of system memory
[!] WARNING: You demanded 3 threads to be created, but you only have 7.1709 GB GPU memory available
[!] WARNING: 10.5 GB of GPU memory is recommended for 3 threads
[!] WARNING: With your current amount of GPU memory available, 2 threads is recommended
[?] USER: Change to the recommended value? [Y/n]: Y
[+] INFO: Upscaling single video file: C:\Users\username\Desktop\heretitle\heretitle\heretitle.mkv
2019-03-01 01:47:57.933123 [+] INFO: Extracted frames is being saved to: G:\Convert\Temp\extracted
2019-03-01 01:47:57.933123 [+] INFO: Upscaled frames is being saved to: G:\Convert\Temp\upscaled
Executing: "G:\Convert\video2x\ffmpeg-4.1-win64-static\bin/ffmpeg.exe" -i "C:\Users\username\Desktop\heretitle\heretitle\heretitle.mkv" "G:\Convert\Temp\extracted"\extracted_%0d.png -y -hwaccel auto
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181017
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Trailing options were found on the commandline.
Input #0, matroska,webm, from 'C:\Users\username\Desktop\heretitle\heretitle\heretitle.mkv':
  Metadata:
    title           : 
    encoder         : libebml v1.3.0 + libmatroska v1.4.0
    creation_time   : 2017-03-22T01:43:04.000000Z
  Duration: 00:29:00.96, start: 0.000000, bitrate: 1455 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 640x478, SAR 1:1 DAR 320:239, 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default) (forced)
    Metadata:
      title           : 
    Stream #0:1(ger): Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s (default) (forced)
    Metadata:
      title           : GER - AC3
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to 'G:\Convert\Temp\extracted\extracted_%0d.png':
  Metadata:
    title           : 
    encoder         : Lavf58.20.100
    Stream #0:0: Video: png, rgb24, 640x478 [SAR 1:1 DAR 320:239], q=2-31, 200 kb/s, 23.98 fps, 23.98 tbn, 23.98 tbc (default) (forced)
    Metadata:
      title           : 
      encoder         : Lavc58.35.100 png
frame=41739 fps=167 q=-0.0 Lsize=N/A time=00:29:00.86 bitrate=N/A speed=6.95x
video:14407542kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[+] INFO: Reading video information
[+] INFO: Framerate: 23.976023976023978
[+] INFO: Starting to upscale extracted images
2019-03-01 01:52:57.566659 [+] INFO: [upscaler] Thread 1 started
2019-03-01 01:52:57.567651 [+] INFO: [upscaler] Thread 0 started
Exception in thread 0:
Traceback (most recent call last):
  File "G:\Python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "G:\Python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "G:\video2x\video2x\bin\waifu2x_caffe.py", line 50, in upscale
    subprocess.call(execute)
  File "G:\Python\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "G:\Python\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "G:\Python\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
PermissionError: [WinError 5] Access Denied
Exception in thread 1:
Traceback (most recent call last):
  File "G:\Python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "G:\Python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "G:\video2x\video2x\bin\waifu2x_caffe.py", line 50, in upscale
    subprocess.call(execute)
  File "G:\Python\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "G:\Python\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "G:\Python\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
PermissionError: [WinError 5] Access Denied


[+] INFO: Upscaling completed
[+] INFO: Converting extracted frames into video
Executing: "G:\Convert\video2x\ffmpeg-4.1-win64-static\bin/ffmpeg.exe" -r 23.976023976023978 -f image2 -s 1920x1440 -i "G:\Convert\Temp\upscaled"\extracted_%d.png -vcodec libx264 -crf 25 -pix_fmt yuv420p "G:\Convert\Temp\upscaled"\no_audio.mp4 -y -hwaccel auto
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181017
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Trailing options were found on the commandline.
[image2 @ 00000292d440b480] Could find no file with path 'G:\Convert\Temp\upscaled\extracted_%d.png' and index in the range 0-4
G:\Convert\Temp\upscaled\extracted_%d.png: No such file or directory
[+] INFO: Conversion completed
[+] INFO: Migrating audio tracks and subtitles to upscaled video
Executing: "G:\Convert\video2x\ffmpeg-4.1-win64-static\bin/ffmpeg.exe" -i "G:\Convert\Temp\upscaled"\no_audio.mp4 -i "C:\Users\username\Desktop\heretitle\heretitle\heretitle.mkv" -c:a copy -c:v copy -c:s copy -map 0:v? -map 1:a? -map 1:s? "G:\Convert\MovieOut\stars-battle.angel.alita.ova.mp4" -y -hwaccel auto
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181017
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Trailing options were found on the commandline.
G:\Convert\Temp\upscaled\no_audio.mp4: No such file or directory
[+] INFO: Program completed, taking 299.76256 seconds
Deleting cache directory: G:\Convert\Temp\extracted
Deleting cache directory: G:\Convert\Temp\upscaled

```

**Comment by K4YT3X** [comment] 2019-03-01 03:09
I'm not really sure why that's happening, but I'm pretty positive that if you run it with admin privilege it will go away. I don't have your environment so I can't do any tests, and online searches didn't give me anything useful yet.

**Comment by Fytcher** [comment] 2019-03-01 14:00
Command prompt is runnung as admin and google didn't return something useful for me either ;/

**Comment by Fytcher** [comment] 2019-03-01 14:00
Funny thing: i can every step/command manually and it worked.

**Comment by K4YT3X** [comment] 2019-03-02 18:39
The problem isn't with the commands that are being executed, it's with the subprocess library that's executing them. I would love to know why it isn't working.

**Comment by K4YT3X** [comment] 2019-03-05 00:45
@Fytcher I've updated the command execution method in the last update. Try it to see if it solves the problem. I had the same problem today and that solved my problem.

**Comment by K4YT3X** [comment] 2019-03-10 15:29
@Fytcher I've made some changes to it in the new version, check to see if the problem is still there.

**Comment by K4YT3X** [comment] 2019-03-12 14:35
Closing this issue since the issue owner didn't respond in a long time.

**Closed by K4YT3X** 2019-03-12 14:35 UTC
Labels: bug, help wanted, question, timed-out
