### ISSUE TITLE
Java Kernel Errors

### ISSUE THREAD

**Issue by IrealiTY** [k4yt3x/video2x#208] opened 2020-03-01 11:49 UTC
## Environment Information

|Module|Version|
|-|-|
|`Video2X`|3.0.0| 
|`FFmpeg`|git-2020-02-18-ebee808 (part of the zip file from Video2x)|
|`waifu2x-caffe`|1.0 (part of the zip file from Video2x)|
|`waifu2x-converter-cpp`| v5.3.3 (master-b45498b) (part of the zip file from Video2x)|
|`waifu2x-ncnn-vulkan`| not sure, but the one from the Video2x 3.0 zip|

## Symptom

```
20614 [+] INFO: Executing: ['C:\\Program Files\\Java\\jdk-12.0.2\\bin\\java.exe', '-jar', 'dependencies\\anime4k\\Anime4K.jar', 'F:\\Video2x\\cache\\tmpdyzlb73r\\0\\extracted_20982.PNG', 'F:\\Video2x\\cache\\tmpc19e17yi\\extracted_20982.PNG', '4.5']
after clEnqueueNDRangeKernel, globalSize[0] = 6998400, localSize[0] = 256
!!!!!!! clEnqueueNDRangeKernel() failed invalid work group size
Mar 01, 2020 12:44:10 PM com.aparapi.internal.kernel.KernelRunner fallBackToNextDevice
WARNING: Device failed for ImageKernel, devices={NVIDIA<GPU>|Java Alternative Algorithm|Java Thread Pool}: OpenCL execution seems to have failed (runKernelJNI returned -54)
com.aparapi.internal.exception.AparapiException: OpenCL execution seems to have failed (runKernelJNI returned -54)
        at com.aparapi.internal.kernel.KernelRunner.executeOpenCL(KernelRunner.java:1263)
        at com.aparapi.internal.kernel.KernelRunner.executeInternalInner(KernelRunner.java:1712)
        at com.aparapi.internal.kernel.KernelRunner.executeInternalOuter(KernelRunner.java:1383)
        at com.aparapi.internal.kernel.KernelRunner.execute(KernelRunner.java:1374)
        at com.aparapi.Kernel.execute(Kernel.java:2897)
        at com.aparapi.Kernel.execute(Kernel.java:2854)
        at com.aparapi.Kernel.execute(Kernel.java:2829)
        at com.bloc97.anime4k.ImageKernel.process(ImageKernel.java:71)
        at com.bloc97.anime4k.Main.main(Main.java:60)
Mar 01, 2020 12:44:10 PM com.aparapi.internal.kernel.KernelRunner fallBackToNextDevice
WARNING: Trying next device: Java Alternative Algorithm
```

## Screenshots or Error Messages

![image](https://user-images.githubusercontent.com/1223686/75625022-549f6b80-5bba-11ea-9787-fd6146dfab32.png)

```
```

**Comment by k4yt3x** [comment] 2020-03-01 22:40
This is a duplicate of #197

**Closed by k4yt3x** 2020-03-01 22:40 UTC
Labels: bug, duplicate
