### ISSUE TITLE
Use more than 1 GPU to do upscaling

### ISSUE THREAD

**Issue by githupper** [k4yt3x/video2x#233] opened 2020-04-30 05:02 UTC
## Description
To allow usage of more than 1 GPU for upscaling task

Briefly describe the feature you want to be added into `video2x`.
Multi-GPU setups in supported games support AFR (alternate frame rendering) to improve performance in gaming. Can we explore similar functionality for Video2x to take advantage of multiple GPUs also?

Video2x itself is aware of how many images were extracted from a said video file source after extraction. Can it assign frames with even numbers to 1 GPU and odd numbers to another GPU?
The images are static and fixed in numbers and perhaps can be assigned to different folders for multiple worker instances of Video2x or multiple scaling processes? 

The suggestion above is a simplistic view of the upscaling process from my layman's point of view so my apologies if it is not functionally feasible. Thanks!

Paste links to descriptions of related documentations, websites and etc. here.
https://en.wikipedia.org/wiki/Alternate_frame_rendering

**Comment by k4yt3x** [comment] 2020-04-30 07:53
Duplicate of #115

**Closed by k4yt3x** 2020-04-30 07:53 UTC
Labels: duplicate, enhancement
