### ISSUE TITLE
Failed to open video file with OpenCV

### ISSUE THREAD

**Issue by zsmlgy** [k4yt3x/video2x#1201] opened 2024-10-29 14:30 UTC
![image](https://github.com/user-attachments/assets/9dc4c2b7-e3c4-4ee2-acce-c39d7ea929e2)

**Comment by k4yt3x** [comment] 2024-10-29 19:06
Turn on debug logging and see why it went wrong.

**Comment by lorsch525** [comment] 2024-10-31 01:29
"Failed to open video file with OpenCV" is the error message.

**Comment by k4yt3x** [comment] 2024-10-31 05:18
That's very interesting. I'll look into it.

**Comment by hansenchen2015** [comment] 2024-11-01 09:45
You can try not to include Chinese characters in the path and file name

**Comment by k4yt3x** [comment] 2024-11-01 14:01
@zsmlgy You can try @hansenchen2015's suggestion. If that solves the issue then the rest is easy. On my system I use UTF-8 for non-English characters, so that might be why it's working for me.

Anyhow, try renaming the file and see if it works.

> other video also can not run

Are they all throwing the same error?

**Comment by lorsch525** [comment] 2024-11-01 14:28
Okay, I tested some more files and can confirm the following: 
- some rare characters in the filename will not work
- some video resolutions don't work (5120x1440 not, however 3840x1440 works, both being 32:9 formats). It is probably the total resolution affecting this rather than the aspect ratio. Have not tested higher resolution 16:9 videos.

**Comment by lorsch525** [comment] 2024-11-01 14:31
The 5120x1440 video throws a different error: 

[2024-11-01 14:30:28.489] [info] Output video dimensions: 20480x5760
[libx264 @ 000002807295e580] invalid width x height (20480x5760)
[2024-11-01 14:30:28.489] [error] Cannot open video encoder
[2024-11-01 14:30:28.489] [error] Failed to initialize encoder: Generic error in an external library

**Comment by k4yt3x** [comment] 2024-11-01 14:43
> some rare characters in the filename will not work

Can you name which characters?

> [libx264 @ 000002807295e580] invalid width x height (20480x5760)

I think you just went above libx264's max supported pixel count or resolution. It's simply too large for it, not a bug.

**Comment by lorsch525** [comment] 2024-11-01 14:55
Characters: I have tested a few from UTF-8: german umlaute, greek symbols, black spades are a few examples that don't work.

The high resolution video: Not a problem, this was just done for testing purposes.

**Comment by k4yt3x** [comment] 2024-11-01 14:57
> Characters: I have tested a few from UTF-8: german umlaute, greek symbols, black spades are a few examples that don't work.

Thanks. I'll see if I can reproduce that locally.

**Comment by k4yt3x** [comment] 2024-11-01 14:59
@lorsch525 I guess you don't have Unicode UTF-8 support turned on in Windows' Region Settings?

**Comment by lorsch525** [comment] 2024-11-01 15:26
> @lorsch525 I guess you don't have Unicode UTF-8 support turned on in Windows' Region Settings?

Okay, after finding that option, activationg UTF-8 support and restarting the computer, finally every file seems to work regardless of the filename. Thank you!
Incredible that this is not activated by default in Windows, this is quite a fresh installation.

**Comment by k4yt3x** [comment] 2024-11-01 16:16
That option is very helpful for solving various compatibility issues, but Windows uses UTF-16 to encode file paths by default, which is what's causing the issue. I'll make a fix so it handles UTF-16 paths correctly as well. I'll close this issue when that fix is pushed.

**Comment by k4yt3x** [comment] 2024-11-05 02:08
This issue should now be fixed in 6.1.0

**Closed by k4yt3x** 2024-11-05 02:08 UTC
Labels: state:waitingForCreator, insufficient information

**Comment by githubusername2024** [comment] 2024-11-06 20:22
I have tried to convert a video from the path below and received the same error with 6.10
E:\a\folder_name12\string string_string12 string string 2024-11-11 11-11, #1 string  string  – string.mkv

**Comment by k4yt3x** [comment] 2024-11-06 21:29
Are you sure you're on 6.1.0? With which client, the GUI?
6.1.0 doesn't even use OpenCV

**Comment by githubusername2024** [comment] 2024-11-06 23:13
Right, I messed something app and used 6.0. Thank you for the reply
