### ISSUE TITLE
add pause for quarry/actuall processing

### ISSUE THREAD

**Issue by Xyz00777** [k4yt3x/video2x#302] opened 2020-06-11 22:19 UTC
a pause button for the actual process (pause only the actual process (also the quarry too)) and for the quarry (let the actual process run finish and than stop the quarry) would awesome. it would be awesome because when you have to shut down the system or the program (for whatever reason) than you could resume at the last point where you was)

**Comment by k4yt3x** [comment] 2020-06-11 22:28
duplicate of #65

**Closed by k4yt3x** 2020-06-11 22:28 UTC
Labels: duplicate
