### ISSUE TITLE
Command '['C:\\Users\\Admin\\Downloads\\video2x-4.8.1-win32-full\\video2x-4.8.1-win32-full\\dependencies\\ffmpeg\\bin\\ffmpeg', '-hwaccel', 'auto', '-y', '-i', 'F:\\Downloads\\Soap-S01e01_1.mkv', '-pix_fmt', 'rgb24', 'F:\\Downloads\\TempCache\\tmpt805fhmv\\extracted_%0d.png']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by jcdick1** [k4yt3x/video2x#656] opened 2022-05-26 22:52 UTC
[video2x_error5.txt](https://github.com/k4yt3x/video2x/files/8782583/video2x_error5.txt)

The relevant item is:

av_interleaved_write_frame(): I/O error

**Comment by k4yt3x** [comment] 2022-05-30 05:36
Duplicate of #653

**Closed by k4yt3x** 2022-05-30 05:36 UTC
