### ISSUE TITLE
input handling bugs

### ISSUE THREAD

**Issue by sat3ll** [k4yt3x/video2x#180] opened 2019-12-26 05:02 UTC
## Environment Information
Linux

|Module|Version|
|-|-|
|`Video2X`|3.0.0 - 2d81270 |
|`FFmpeg`|4.2.1|

## Bug 1
requirements.txt file has not been updated since at least the introduction of the tk GUI.

## Bug 2
`video2x.py -i /tmp/test.mp4 -d waifu2x_ncnn_vulkan -o /tmp/lma.mp4`
Will yield:
```
Traceback (most recent call last):
  File "/app/bin/video2x.py", line 274, in <module>
    if args.driver == 'waifu2x_ncnn_vulkan' and (args.ratio > 2 or not args.ratio.is_integer()):
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```
Proposal:
- args.ratio comparison for vulkan should come after checking validity of arg.ratio (nested if ?)

## Bug 3 [not a bug]
FFmpeg fails in frame extracting phase
```
[NULL @ 0x555b172b78c0] Unable to find a suitable output format for '/tmp/video2x/tmpa32p_6g4/extracted_%0d.png'
/tmp/video2x/tmpa32p_6g4/extracted_%0d.png: Invalid argument
```
Tried reducing options to no avail. Appending "-f": "png" will result in:
```
[NULL @ 0x55be18946300] Requested output format 'png' is not a suitable output format
/tmp/video2x/tmp4r7f7og7/extracted_%0d.png: Invalid argument
```
Command:
```
subprocess.CalledProcessError: Command '['/usr/bin/ffmpeg', '-hwaccel', 'auto', '-y', '-i', '/tmp/test.mkv', '-pix_fmt', 'rgba64be', '-f', 'png', '/tmp/video2x/tmp4r7f7og7/extracted_%0d.png']' returned non-zero exit status 1.
```
This could be related to subprocess or whatever component handling those "%" symbols.

**Comment by sat3ll** [comment] 2019-12-26 13:39
## Bug #4
waifu2x_ncnn_vulkan is not ready for YAML configuration.
https://github.com/k4yt3x/video2x/blob/2d81270e44564dff9b6eebe4702adf9d8e111e49/src/waifu2x_ncnn_vulkan.py#L40
```
[+] INFO: Framerate: 23.976023976023978
[+] INFO: Starting to upscale extracted images
[!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "/app/bin/video2x.py", line 398, in <module>
    upscaler.run()
  File "/app/bin/upscaler.py", line 357, in run
    self._upscale_frames()
  File "/app/bin/upscaler.py", line 247, in _upscale_frames
    w2 = Waifu2xNcnnVulkan(copy.deepcopy(self.driver_settings))
  File "/app/bin/waifu2x_ncnn_vulkan.py", line 40, in __init__
    os.chdir(os.path.join(self.driver_settings['waifu2x_ncnn_vulkan_path'], '..'))
KeyError: 'waifu2x_ncnn_vulkan_path'
```

**Comment by k4yt3x** [comment] 2020-01-04 22:00
I was not able to reproduce bug3.
Everything else should be fixed.

**Comment by sat3ll** [comment] 2020-01-04 22:02
Bug 3 turned out to be a 'lite' build of ffmpeg. Disregard it

**Comment by k4yt3x** [comment] 2020-01-04 22:04
Ok then, all bugs in this issue are fixed.

**Closed by k4yt3x** 2020-01-04 22:04 UTC
Labels: bug
