### ISSUE TITLE
'frames' folder split leaving random frame out, breaking post-upscale encode step

### ISSUE THREAD

**Issue by cr08** [K4YT3X/video2x#23] opened 2018-11-05 15:29 UTC
Decided to give this a go on a test video this morning. A roughly 22-25 minute video with approx. 35k frames. One thing I ran into is that somewhere during the process where it breaks the frames out into equal folders depending on the number of upscaler threads use for whatever reason in my test left out a single frame. So essentially I had this:

frames
-- \0\
-- \1\
-- \2\
-- \extracted_9999.png

Btw, that frame number is correct in my scenario and not just a placeholder

So with that lone frame outside those folders, after upscaling was done there was a single frame gap in the upscaled folder. It then cascaded to the following ffmpeg encode step failing at that frame number because it couldn't find it.

FWIW it recommended dropping down to 3 threads which I did so not sure how related that would be here. Despite the fact it never seems to use much more than about 1GB extra tops over my normal load leaving about 7GB free still and just 1GB VRAM used on my 6GB 1060 MaxQ. Though it seemed to load the system down pretty well with the Compute load up around 85% and CPU (i7-7700HQ) regularly around 90%. Took about 2.5 hours just for the upscale portion for 35k frames.

**Comment by K4YT3X** [comment] 2018-11-05 15:43
@cr08 I'll will take a look at this problem.
The multi-threading function has just been added not too long ago, and this might as well be a fatal bug.

As for the performance, here's what I got on my system.
- My 16 DDR4 is used up to 95% when upscaler threads are initializing, and soon it drops down to normal, so does the CPU usage drop down quite a bit.
- The GPU computing usage gets up to 90-100% for the entire duration of the upscaling, while the VRAM is only half-filled.

**Comment by K4YT3X** [comment] 2018-11-05 15:55
Also, make sure you're using the newest version of video2x. The latest changes has been made for fixing bugs within the multithreading function.

Also, the part where video2x places frames into folders it at line 150, video2x.py. Maybe you can find some issues there?

**Comment by cr08** [comment] 2018-11-05 17:20
I'm running the latest commit. Downloaded fresh this morning.

I wonder if it might be a simple math issue. I rechecked and the exact number of frames in this video is 35,763. 3 threads means it is divided up to 11,891 frames per thread with one frame left over.

**Comment by K4YT3X** [comment] 2018-11-05 17:24
@cr08 I think that's exactly where the problem is.

I'm running Kali right now and doesn't have access to a windows workstation at the moment. I'll make the changes when I get back home.

Or you can submit a pull request (wink :P

**Comment by K4YT3X** [comment] 2018-11-05 17:44
@cr08 Actually, never mind. I was able to RDP into my server and test the patch.
I have just pushed a new commit into the repo which should fix the problem.

This might be a less stupid way of distributing images evenly.
```
    # Evenly distribute images into each folder
    # until there is none left in the folder
    for image in frames:
        # Move image
        shutil.move(image, thread_folders[0])
        # Rotate list
        thread_folders = thread_folders[-1:] + thread_folders[:-1]
```

**Comment by cr08** [comment] 2018-11-06 03:55
So far so good. Ran a few shorter clips through with varying frame counts and no issues.

**Comment by K4YT3X** [comment] 2018-11-06 14:21
If all's fine, then I'll close this issue.
We can reopen it any time if it's still malfunctioning.

**Closed by K4YT3X** 2018-11-06 14:21 UTC
Labels: bug
