### ISSUE TITLE
Error when scaling is more than 2.00, or when scale width or height is more than 2 times the resolution of original file

### ISSUE THREAD

**Issue by MrCB08** [k4yt3x/video2x#316] opened 2020-07-19 07:17 UTC
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 4.6.0
- **Upscaler version**: Waifu2x Caffe (Latest)
- **GUI version**: 2.7.1
- **CLI version**: 4.1.1

## Symptom

When I use the GPU (Nvidia), whenever the scaling is 2.50 or higher, or when the using the scale width and height in the Waifu2X Caffe settings with a resolution that's more than twice of the original video file, it stops and an error message appears.
 

## Error Log or Screenshots

![image](https://user-images.githubusercontent.com/56218268/87869470-b9752a00-c9d2-11ea-9b0e-5d6716590e52.png)

Log file:
[video2x_2020-07-19_15-13-24.log](https://github.com/k4yt3x/video2x/files/4943374/video2x_2020-07-19_15-13-24.log)

**Comment by mason1171** [comment] 2020-07-19 07:55
It looks like your card doesn't have enough memory to handle that large of an upscale

- What GPU do you have? How many VRAM?

- Try reducing the crop size

**Comment by MrCB08** [comment] 2020-07-19 08:23
My GPU is a 940MX which only has 2GB VRAM unfortunately. Also tried reducing size the crop size until the lowest value and still failed.

**Comment by mason1171** [comment] 2020-07-19 15:15
It look like your card isn’t capable of that high of an upscale. Try a different engine

**Comment by MrCB08** [comment] 2020-07-19 16:08
Oh well, I'll do what I can with this until I can upgrade to better hardware.
I tried all the models for caffe and what worked for me was:
- anime_style_art
- anime_style_art_rgb
- upconv_7_anime_style_rgb
- upconv_7_photo
But, I used a lower resolution file (360p) compared to the previous one (480p) where nothing worked.

Still, thank you!

**Comment by mason1171** [comment] 2020-07-19 16:53
Try using the anime4K engine or one of the other Waifu2x ones

**Comment by k4yt3x** [comment] 2020-07-19 20:45
I'd say try waifu2x-ncnn-vulkan with cunet model (default).
It should deliver comparable results.

**Comment by k4yt3x** [comment] 2020-07-21 05:47
The issue is already resolved, hence closing this thread.

**Closed by k4yt3x** 2020-07-21 05:47 UTC
Labels: type:Question
