### ISSUE TITLE
Exception has occurred with specified video2x_cache_folder

### ISSUE THREAD

**Issue by cr08** [k4yt3x/video2x#78] opened 2019-04-09 22:58 UTC
## Environment Information

|Module|Version|
|-|-|
|`video2x`|[latest commit](https://github.com/k4yt3x/video2x/commit/405c4b66363c534eda8c08f4820080497c7bb1d3)|
|`ffmpeg`|'latest' version N-93506-g27c94c57dc|
|`waifu2x-caffe`|1.0.0|
|`waifu2x-converter-cpp`||

## Symptom

Specifying a video2x_cache_folder in the json config errors out and won't continue to the initial video-to-frame stage. Leaving the config unspecified allows it to proceed normally using system temp folders.

The folder/drive in question in the screenshot below is writable and should have no issues.

## Screenshots or Error Messages

![tempsnip](https://user-images.githubusercontent.com/1199481/55840145-6d151c00-5af8-11e9-9f60-a9b25a3f6e10.png)

```
```

**Comment by k4yt3x** [comment] 2019-04-10 00:25
Hmm I'm actually not sure what's going on.
It might have to take me a while to find time to fix this as exam week is approaching.

**Comment by cr08** [comment] 2019-04-18 01:59
Not completely sure but after trying to implement a hacky workaround in the meantime under upscaler.py around lines 55-63 it appears it may be overriding what is in video2x.py? After hardcoding a different folder over in video2x.py it still seemed to want to throw that error and point to the %temp% directory and it is indicating that is failing under upscaler.py.

**Comment by k4yt3x** [comment] 2019-04-18 03:30
I suddenly understand why the error occured. The variables used to be passed to the upscaler class upon Upscaler initialization, but when I changed the way they're being passed, video2x cache folder is set to default.

Anyways, I know where the problem is. I'll fix it right after the exam is done.

**Comment by k4yt3x** [comment] 2019-04-18 18:57
@cr08 It's fixed in the newest update.

**Closed by k4yt3x** 2019-04-18 18:57 UTC
Labels: bug, help wanted
