### ISSUE TITLE
Failed upscaling gifs

### ISSUE THREAD

**Issue by makrker** [k4yt3x/video2x#578] opened 2021-12-14 01:51 UTC
## Component Versions

- **Video2X release version**:
- from git / 4.3.3
- **Upscaler version**:
-  waifu2x 20210521-1
- **GUI version**:
- from git / 4.3.3
- **CLI version**:
from git / 4.3.3
## Symptom
Failed upscaling gifs 

## Error Log or Screenshots
[video2x_an36z2b4.log](https://github.com/k4yt3x/video2x/files/7708040/video2x_an36z2b4.log)
terminal 
![Screenshot_2021-12-14-08-45-44_1920x1080](https://user-images.githubusercontent.com/86200419/145918036-ec84416a-26d3-416e-8678-832a41ed9fe7.png)

**Comment by k4yt3x** [comment] 2021-12-14 16:40
> error: Unable to find the input file: "/tmp/video2x/tmpx6_u01ou/extracted_*.png"
> The path contains a literal "*" character. If you want to select multiple files, don't put the special wildcard characters in quotes.

Looks like a known problem, duplicate of #343. For now, you can preserve the frames and use Gifski to create the GIF manually.

**Closed by k4yt3x** 2021-12-14 16:40 UTC
Labels: type:Bug, duplicate
