### ISSUE TITLE
English cannot be selected, font used changes

### ISSUE THREAD

**Issue by reindex-ot** [k4yt3x/video2x#1195] opened 2024-10-23 22:22 UTC
Even if I select English from the Language menu, it always becomes Japanese.
If you specify Japanese at the same time, Chinese fonts will be loaded.

#### Japanese (English Selected) - Japanese font loaded
![Jpanaese](https://github.com/user-attachments/assets/5843c03b-a5a3-49c5-817f-fc00f3864433)

#### Japanese (Japanese Selected) - Chinese font loaded
![ChineseFont_Japanese](https://github.com/user-attachments/assets/e8fafc78-432b-4d79-ba79-48b88cc43c46)

**Comment by k4yt3x** [comment] 2024-10-25 04:24
I was able to reproduce the issue. Since the English locale has an empty translation file, when you select English in a system that's using one of the other languages as the default locale, it switches to that language instead. I'll work on a fix.

**Comment by k4yt3x** [comment] 2024-10-25 20:34
It's been fixed in this commit: https://github.com/k4yt3x/video2x-qt6/commit/911cc860a4c34930fd40f3a998b057f3e0ea52d6.
Will be included in the next release.
Thanks for the bug report. Closing the issue.

**Closed by k4yt3x** 2024-10-25 20:34 UTC
Labels: type:Bug, component:GUI
