### ISSUE TITLE
RealSR crashed without logs

### ISSUE THREAD

**Issue by Cireus** [k4yt3x/video2x#584] opened 2022-01-01 04:07 UTC
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 2.8.1

## Symptom

Ran into an error around 20 hours in

If any other information needed that isn't present please let me know where to find it so I can give it.

## Error Log or Screenshots
[video2x_error.log](https://github.com/k4yt3x/video2x/files/7797362/video2x_error.log)

**Comment by k4yt3x** [comment] 2022-02-06 20:10
Looks like realsr just... died? I'm don't see any error messages related to why it crashed.

**Comment by k4yt3x** [comment] 2022-04-24 07:01
There has been other reports of similar issues, the cause is unclear, but it has not been observed so far in 5.0.0. I'm closing this since 4.8.1's code can't be changed anymore.

**Closed by k4yt3x** 2022-04-24 07:01 UTC

**Comment by gyan0001** [comment] 2024-09-08 04:15
> Looks like realsr just... died? I'm don't see any error messages related to why it crashed.

Where and how to use that log file on Video 2x ??? .........
