### ISSUE TITLE
Specified Driver executable directory doesn't exit. Pleasse check the configuration file settings.

### ISSUE THREAD

**Issue by Subash-Chandra** [k4yt3x/video2x#175] opened 2019-12-02 00:21 UTC
## Environment Information

|Module|Version|
|-|-|
|`Video2X`|latest|
|`FFmpeg`|latest|
|`waifu2x-caffe`|latest|
|`waifu2x-converter-cpp`|none|
|`waifu2x-ncnn-vulkan`|none|

## Symptom
An error is thrown saying that it is looking within C:Users\K4YT3X\AppData\Local....
Is this intended?

## Screenshots or Error Messages

Please paste screenshots or error messages here.
![image](https://user-images.githubusercontent.com/29782637/69923032-ffdb4000-1466-11ea-8b21-ee57431c92e6.png)

Include as much details as you can, as this greatly helps debugging the problem.

Please paste your error message in the code block down below:

```
[!] ERROR: Specified driver executable directory doesn't exist
[!] ERROR: Please check the configuration file settings
Traceback (most recent call last):
  File "video2x.py", line 319, in <module>
    raise FileNotFoundError(driver_settings['path'])
FileNotFoundError: C:\Users\K4YT3X\AppData\Local\video2x\waifu2x-caffe\waifu2x-caffe-cui
```

**Comment by k4yt3x** [comment] 2019-12-02 02:26
Did you setup the environment properly?
(did you run the setup script?)

**Comment by Subash-Chandra** [comment] 2019-12-02 04:17
Yup. I ran the setup script. It says it's looking for your (K4YT3X's) appdata/local folder. Is that the problem?

**Comment by Subash-Chandra** [comment] 2019-12-02 04:25
I thought it might have been because i installed mine on a secondary drive and not on my C:\....\appdata\local, so i reinstalled it just with the git clone etc, and ran everything again. When i tried to run it this time, it gave me this error


```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "video2x_gui.py", line 343, in _upscale
    self.upscaler = Upscaler(input_video=input_file, output_video=output_file, method=method, waifu2x_settings=waifu2x_settings, ffmpeg_settings=ffmpeg_settings)
TypeError: __init__() got an unexpected keyword argument 'waifu2x_settings'
```

**Comment by k4yt3x** [comment] 2019-12-03 00:19
I'll investigate this further when I'm done with my finals.

**Comment by k4yt3x** [comment] 2019-12-12 02:59
This issue has been fixed in https://github.com/k4yt3x/video2x/commit/9e745fb74703794b795856d790e989c69b433efd

The issue was caused by incompatibility between the old video2x_gui and the new video2x.

**Closed by k4yt3x** 2019-12-12 02:59 UTC
Labels: bug
