### ISSUE TITLE
Issues I found after some long nights of testing

### ISSUE THREAD

**Issue by metzo007** [k4yt3x/video2x#87] opened 2019-04-29 22:21 UTC
Issues I found after some long nights of testing

Hi,
I did a lot of test with a lot of differend computers and would like to share the results

A GTX 950 will not work at all because it has only 2GB memory
A GTX 970 will work with one thread, and same goes for the 1050 Ti

However, on all my tests I was only able to get the "-r 2" working. Using  "-r 3" or higher alway results in errors. But I was working to use the  "-r 2" twice in a row to get a higher resolution. 

Chosing a custum resuliution only works if is was the same as in "-r 2". Using "--width=1920 --height=1080" on a 640x480 video failed on all tested systems. For 640 x 480 only "--width=1280 --height=960" will work

Overall It would be a great improvement to get the memory usage below 2 GB to get older GPUs working. 

Thanks for the great tool, If it works the results are amazing :-)

**Comment by k4yt3x** [comment] 2019-04-29 23:10
Hi @metzo007, the RAM usage is not determined by video2x, but rather waifu2x. Therefore, there's really not much I can do about this.

If you want to try some different approaches, try the `waifu2x-converter-cpp` driver.

> However, on all my tests I was only able to get the "-r 2" working. Using "-r 3" or higher alway results in errors. But I was working to use the "-r 2" twice in a row to get a higher resolution.

I'll look into this.

**Comment by k4yt3x** [comment] 2019-04-30 05:22
I just tried `-r3` on the sample video and everything seems to work just fine.

**Comment by metzo007** [comment] 2019-04-30 06:21
where do I find the sample video? 

This is the error I get on a 640x480 using -r 3

[+] INFO: Starting to upscale extracted images
2019-04-30 08:11:12.741585 [+] INFO: Starting upscaled image cleaner
2019-04-30 08:11:12.744585 [+] INFO: [upscaler] Thread 0 started
2019-04-30 08:11:12.745582 [+] INFO: Executing: ['C:\\video2x\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui.exe', '--output_extention', 'png', '--mode', 'noise_scale', '--scale_ratio', '3.0', '--noise_level', '3', '--process', 'gpu', '--crop_size', '128', '--output_quality', '-1', '--output_depth', '8', '--batch_size', '1', '--gpu', '0', '--tta', '0', '--input_path', 'C:\\Users\\Xeon\\AppData\\Local\\Temp\\video2x\\tmp7f9p07zg\\0', '--output_path', 'C:\\Users\\Xeon\\AppData\\Local\\Temp\\video2x\\tmps5f86frf']
Upscaling Progress:   0%|                                                                     | 0/6159 [00:02<?, ?it/s]Could not create log file: File exists
COULD NOT CREATE LOGFILE '20190430-081115.9120'!
F0430 08:11:15.270328  4368 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
Upscaling Progress:   0%|                                                                     | 0/6159 [00:05<?, ?it/s]2019-04-30 08:11:18.465377 [+] INFO: Killing upscaled image cleaner
Upscaling Progress:   0%|                                                                     | 0/6159 [00:06<?, ?it/s][!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "video2x.py", line 306, in <module>
  File "upscaler.py", line 293, in run
  File "upscaler.py", line 232, in _upscale_frames
  File "waifu2x_caffe.py", line 83, in upscale
  File "subprocess.py", line 487, in run
subprocess.CalledProcessError: Command '['C:\\video2x\\dependencies\\waifu2x-caffe\\waifu2x-caffe-cui.exe', '--output_extention', 'png', '--mode', 'noise_scale', '--scale_ratio', '3.0', '--noise_level', '3', '--process', 'gpu', '--crop_size', '128', '--output_quality', '-1', '--output_depth', '8', '--batch_size', '1', '--gpu', '0', '--tta', '0', '--input_path', 'C:\\Users\\Xeon\\AppData\\Local\\Temp\\video2x\\tmp7f9p07zg\\0', '--output_path', 'C:\\Users\\Xeon\\AppData\\Local\\Temp\\video2x\\tmps5f86frf']' returned non-zero exit status 3221226505.
[!] WARNING: If you experience error "cudaSuccess out of memory", try reducing number of threads you're using

looks like a memory issue, but with the 4 GB 970 I should have headroom to run at least 1 thread.

**Comment by k4yt3x** [comment] 2019-04-30 06:40
> cudaSuccess (2 vs. 0) out of memory

You're simply out of memory.

**Comment by metzo007** [comment] 2019-04-30 07:05
got it :-)
So its save to say that for a SD to FullHD you need a 8 GB Card at least, but with a 4 GB Card you can still go from SD to HDready and FullHD in two convertions. 

What card can you recommend?

**Comment by k4yt3x** [comment] 2019-04-30 16:30
> What card can you recommend?

I'm not rich enough to have used multiple cars to be able to give you an suggestion. I personally use a 1060 6G and it works okay for me for most tasks.

I don't get how your card can't even run just one thread. Does `waifu2x-converter-cpp` work?

**Comment by WSADKeysGaming** [comment] 2019-04-30 16:35
Is crop size editable in the JSON file? Sorry, I haven't used this program
in a few months so I don't know what updates were made :). I know that
using -cudnn decreases VRAM using and so does decreasing crop size to 64 in
w2x-caffe.

**Comment by metzo007** [comment] 2019-04-30 19:08
Funny

using the waifu2x-converter-cpp go the 2GB GTX 950 to work, but will not work with the 4GB 1050 TI

with the 1050 I get this error message

[+] INFO: Starting to upscale extracted images
2019-04-30 20:58:21.441202 [+] INFO: [upscaler] Thread MainThread started
2019-04-30 20:58:21.441202 [+] INFO: Executing: ['C:\\video2x\\dependencies\\waifu2x-converter-cpp\\waifu2x-converter-cpp.exe', '--output-format', 'png', '--jobs', '1', '--model-dir', 'C:\\video2x\\dependencies\\waifu2x-converter-cpp\\models_rgb', '--scale-ratio', '2.0', '--noise-level', '3', '--mode', 'noise-scale', '--silent', '--output', 'C:\\Users\\DELLGA~1\\AppData\\Local\\Temp\\video2x\\tmp4cwosfvh', '--input', 'C:\\Users\\DELLGA~1\\AppData\\Local\\Temp\\video2x\\tmpx57p77u7']
Upscaling Progress:   0%|                                                                                                                                 | 0/13073 [00:00<?, ?it/s]CUDA: GeForce GTX 1050 Ti
We're going to be operating in a directory. dir:C:\Users\DELLGA~1\AppData\Local\Temp\video2x\tmpx57p77u7
Upscaling Progress:   0%|                                                                                                                                 | 0/13073 [00:01<?, ?it/s][Upscaling Progress:   0%|                                                                                                                                 | 0/13073 [00:03<?, ?it/s]
[+] INFO: Upscaling completed
[+] INFO: Converting extracted frames into video
2019-04-30 20:58:25.536587 [+] INFO: Executing: ['C:\\video2x\\dependencies\\ffmpeg-latest-win64-static\\bin\\ffmpeg.exe', '-r', '29.97', '-s', '1152x640', '-i', 'C:\\Users\\DELLGA~1\\AppData\\Local\\Temp\\video2x\\tmp4cwosfvh\\extracted_%d.png', 'C:\\Users\\DELLGA~1\\AppData\\Local\\Temp\\video2x\\tmp4cwosfvh\\no_audio.mp4', '-f', 'image2', '-vcodec', 'libx264', '-crf', '25', '-pix_fmt', 'yuv420p', '-hwaccel', 'auto', '-y']
ffmpeg version N-93485-g5282cbae61 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20190212
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 26.100 / 56. 26.100
  libavcodec     58. 47.106 / 58. 47.106
  libavformat    58. 26.101 / 58. 26.101
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 48.100 /  7. 48.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
Trailing options were found on the commandline.
[image2 @ 00000224d79ca0c0] Could find no file with path 'C:\Users\DELLGA~1\AppData\Local\Temp\video2x\tmp4cwosfvh\extracted_%d.png' and index in the range 0-4
C:\Users\DELLGA~1\AppData\Local\Temp\video2x\tmp4cwosfvh\extracted_%d.png: No such file or directory
[!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "video2x.py", line 306, in <module>
  File "upscaler.py", line 300, in run
  File "ffmpeg.py", line 108, in convert_video
  File "ffmpeg.py", line 147, in _execute
  File "subprocess.py", line 487, in run
subprocess.CalledProcessError: Command '['C:\\video2x\\dependencies\\ffmpeg-latest-win64-static\\bin\\ffmpeg.exe', '-r', '29.97', '-s', '1152x640', '-i', 'C:\\Users\\DELLGA~1\\AppData\\Local\\Temp\\video2x\\tmp4cwosfvh\\extracted_%d.png', 'C:\\Users\\DELLGA~1\\AppData\\Local\\Temp\\video2x\\tmp4cwosfvh\\no_audio.mp4', '-f', 'image2', '-vcodec', 'libx264', '-crf', '25', '-pix_fmt', 'yuv420p', '-hwaccel', 'auto', '-y']' returned non-zero exit status 1.
[!] WARNING: If you experience error "cudaSuccess out of memory", try reducing number of threads you're using

**Comment by k4yt3x** [comment] 2019-05-06 01:47
@metzo007 as far as what I can see, waifu2x-converter-cpp didn't really do anything and just stopped.
Not sure why.
Try changing silent to false in the config file and run it again to see what happened.

**Comment by k4yt3x** [comment] 2019-05-06 01:47
@WSADKeysGaming 
![image](https://user-images.githubusercontent.com/21986859/57203585-6787e600-6f7f-11e9-9046-22fbf8222e2e.png)

**Comment by k4yt3x** [comment] 2019-05-08 00:46
The causes of the problems have been identified, and the issue owner didn't reply in a while. Closing the issue.

**Closed by k4yt3x** 2019-05-08 00:46 UTC
Labels: bug
