### ISSUE TITLE
Docker image - can't find /video2x/src/dependencies/anime4kcpp/anime4kcpp

### ISSUE THREAD

**Issue by Spazzlo** [k4yt3x/video2x#345] opened 2020-09-02 00:27 UTC
## Component Versions

Please at least fill in the release version and GUI or CLI version.

- **Video2X release version**: 4.6.0
- **Upscaler version**:
- **GUI version**: None
- **CLI version**: 4.1.1

## Symptom

Trying to upscale a video with anime4kcpp errors out, saying it can't find the driver.

## Error Log or Screenshots

Command: `docker run --rm -it --gpus all -v /dev/dri:/dev/dri -v $PWD:/host k4yt3x/video2x:4.6.0 -i "Episode 2.mkv" -o a4k.mkv -r 2 -d anime4kcpp`
Output:
```
2020-09-02 00:11:37.243563 [+] INFO: Redirecting console logs to /video2x/src/video2x_2020-09-02_00-11-37.log
[+] INFO: Loading files into processing queue
2020-09-02 00:11:37.270703 [+] INFO: Input path(s): Episode 2.mkv
[!] ERROR: Specified driver executable directory doesn't exist
[!] ERROR: Please check the configuration file settings
[!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "/video2x/src/video2x.py", line 259, in <module>
    upscaler.run()
  File "/video2x/src/upscaler.py", line 513, in run
    self._check_arguments()
  File "/video2x/src/upscaler.py", line 223, in _check_arguments
    raise FileNotFoundError(driver_path)
FileNotFoundError: /video2x/src/dependencies/anime4kcpp/anime4kcpp
```

I'd provide my logs, but they're in the docker image, so I'm not sure how to get to them.

**Comment by k4yt3x** [comment] 2020-09-02 01:56
Duplicate of #325

**Comment by k4yt3x** [comment] 2020-09-02 01:56
The docker build doesn't yet contain Anime4KCPP. I'm still trying to figure out how to build it.

**Closed by k4yt3x** 2020-09-02 01:56 UTC
Labels: duplicate

**Comment by Spazzlo** [comment] 2020-09-02 02:49
Just built it. I needed to install `libopencv-dev`, `opencl-dev`, `libqt5svg5-dev`, and `qttools5-dev`, but other than that, it was just as simple as running `cmake .` then `make`. I'd be happy to try to help you build it yourself to add to the image.

**Comment by k4yt3x** [comment] 2020-09-02 04:55
I'll be working on that shortly.

**Comment by k4yt3x** [comment] 2020-09-03 00:17
I ran into some issues. I've opened a issue in Anime4KCPP's repo. You can take a look at it as well in case you have and leads.
https://github.com/TianZerL/Anime4KCPP/issues/41

**Comment by Spazzlo** [comment] 2020-09-07 04:44
Seems that issue on a4k was closed. Any news of this making it into the docker image?

**Comment by k4yt3x** [comment] 2020-09-07 14:27
#325 is not yet closed. I'm still working on it. Currently stuck at https://github.com/TianZerL/Anime4KCPP/issues/42
