### ISSUE TITLE
Do you guys need 3080 Performance numbers?

### ISSUE THREAD

**Issue by theboee** [k4yt3x/video2x#404] opened 2020-11-03 00:42 UTC
I was lucky enough to score a 3080 FE, do you guys want some performance numbers from the card to put on your benchmark tab?

**Comment by k4yt3x** [comment] 2020-11-04 19:33
Of course! As far as I know, a lot of people are looking forward to benchmark numbers from the 30 series cards.
It will be great if you can run some tests and add your results to the Wiki page: https://github.com/K4YT3X/video2x/wiki/Performance-Benchmarks

**Comment by theboee** [comment] 2020-11-05 05:25
I'm benching the card now. Results so far are indicative of an upwards curve on time. Meaning longer run times seem to benefit the most from the card.

**Comment by k4yt3x** [comment] 2020-12-13 22:03
I'm closing this thread since it's not a bug for me to fix.

**Closed by k4yt3x** 2020-12-13 22:03 UTC
Labels: component:Documentation, type:Discussion
