### ISSUE TITLE
include "attachment" (t) stream for fonts

### ISSUE THREAD

**Issue by ArmandBernard** [K4YT3X/video2x#45] opened 2019-03-01 17:56 UTC
The attachments stream is usually used to hold fonts for subtitles, one example where this is used is the latest season of JoJo, HorribleSubs release. To copy it over from the source file, the following code can be used in ffmpeg:

`-c:t copy -map 1:t? `

**Comment by cr08** [comment] 2019-03-01 19:22
As a suggestion it may be simpler to go to the command line options I used in the following comment or some equivalent: https://github.com/K4YT3X/video2x/issues/24#issuecomment-438329947 Essentially it should copy all streams over from the input file regardless of type and just ignore the original video stream (since we are upscaling and providing a new copy of course). I'm not sure if there's any reason we should potentially be ignoring certain streams and not just keeping the original intact 1:1 save for the upscaled video.

**Comment by K4YT3X** [comment] 2019-03-04 04:08
@cr08 ok. I'll follow your suggestions and try it out.

**Comment by K4YT3X** [comment] 2019-03-04 04:42
I have made a test with your solution, but it didn't seem to copy anything over besides the video stream.

```
-map 1:v:0 -map 0 -c copy -map -0:v
```

**Comment by cr08** [comment] 2019-03-04 13:21
I had a look through again and it may be the input videos are flipped around in the ffmpeg command. Right now the no_audio.mp4 is coming first. So either the above options need to be flipped to

`-map 0:v:0 -map 1 -c copy -map -1:v`

or flip around the input **-i** parameters so the no_audio.mp4 comes second.

I'm running a quick test on my end to confirm.

**Comment by K4YT3X** [comment] 2019-03-04 14:02
Oops you're right. I changed it to

```
-map 0:v:0? -map 1? -c copy -map -1:v?
```

I don't know if it's necessary to add the `?`s, is it?
Everything is looking good right now though. All streams have been copied over.

**Comment by cr08** [comment] 2019-03-04 14:31
Theoretically the question marks shouldn't be needed. Based on how I am reading the documentation it is only necessary if there is a possibility of that map not existing so the command doesn't outright fail, it just ignores that map.

`-map 0:v:0?`
^ We know the input video track is going to exist there from the no_audio.mp4 file

`-map 1?`
^ We know the source input file should still exist at this stage and the map is just saying to grab everything regardless of track type. The only POTENTIAL issue I could see is if someone deletes the input file mid-way through running the script but I don't know why they would?

`-map -1:v?`
^ Much like the last map, the original source file we know should have a video track that needs to be cancelled out. 

With that all said there's nothing harmful leaving the question marks in there, just extraneous characters.

**Comment by cr08** [comment] 2019-03-04 15:29
And confirmed on my end that swapping those around works just fine with my test content.

**Comment by K4YT3X** [comment] 2019-03-05 00:44
Changes committed. It should be working now.

**Closed by K4YT3X** 2019-03-05 00:44 UTC
Labels: enhancement
