### ISSUE TITLE
PIL.Image.DecompressionBombError: Image size (195084288 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack

### ISSUE THREAD

**Issue by VasilyKitty** [k4yt3x/video2x#662] opened 2022-06-03 16:53 UTC
I have seen that some other people opened similar issues, though I'm not sure how to proceed.
Trying to upscale an image 4x with RealSR and getting this error. Other drivers do not give me this error. Is the image simply too large?

[video2x_error.log](https://github.com/k4yt3x/video2x/files/8834243/video2x_error.log)

**Comment by k4yt3x** [comment] 2022-06-04 16:51
Duplicate of #473. Has been fixed in 5.0.0. I've tried to apply the patch to 4.8.1 without luck since I don't have the original dev environment for it anymore.

**Closed by k4yt3x** 2022-06-04 16:51 UTC
