### ISSUE TITLE
Video and Sound not matching!

### ISSUE THREAD

**Issue by Pete4K** [k4yt3x/video2x#1269] opened 2024-12-21 16:38 UTC
Every video's sound is not matching anymore using Real ESRGAN. Before it was matching with the standard setting every time.

**Comment by k4yt3x** [comment] 2024-12-21 19:52
Any chance you send me a video so I can test it?

**Comment by Pete4K** [comment] 2024-12-21 19:58
I try so send some test here. One moment.

**Comment by k4yt3x** [comment] 2024-12-21 20:04
It should be related to this:

> Fixed: Make the encoder always use the calculated PTS with corrected math.

The math works out for the videos I tested with. My tests probably didn't cover all the cases.

**Comment by Pete4K** [comment] 2024-12-21 20:23
https://github.com/user-attachments/assets/208190ca-a2d9-45bc-8b63-bed9935c3707

Here you can see at 0:33 and so on. The difference between audio and video gets bigger and bigger. I made the file very small.

**Comment by Pete4K** [comment] 2024-12-21 20:24
The basic file works normally. Everything I tried was like this clip above.

**Comment by k4yt3x** [comment] 2024-12-21 20:28
Hmm I think it's probably my integer math losing precision as time increases. This might fix it:

![image](https://github.com/user-attachments/assets/90ffdf6b-92ce-405c-a4f9-f884a9d10ba6)

Can you send me the original video so I can test it?

**Comment by k4yt3x** [comment] 2024-12-21 20:29
Via Google Drive, https://wormhole.app or something

**Comment by Pete4K** [comment] 2024-12-21 20:36
https://wormhole.app/W1zBe#ptmxQmpC17-wTkpKRW8hfQ

**Comment by Pete4K** [comment] 2024-12-21 20:37
Try it, I think I should delete this immediately after

**Comment by k4yt3x** [comment] 2024-12-21 20:47
It's taking forever to download. I'm guessing you're still uploading as I download. I'll leave it running for now. Once I finish download I'll delete the file.

**Comment by Pete4K** [comment] 2024-12-21 21:08
For me it is uploaded now. How long does it still run for you?

**Comment by k4yt3x** [comment] 2024-12-21 21:24
It got stuck for a long time so I used another browser which finished downloading in seconds. I just finished downloading and deleted the share.

**Comment by Pete4K** [comment] 2024-12-21 21:26
Ok, thanks.

**Comment by k4yt3x** [comment] 2024-12-21 21:37
I think my patch fixed it. Take a look:
https://wormhole.app/802a7#-3k0W8gUgnOXlSosW0ewTg

**Comment by Pete4K** [comment] 2024-12-21 21:52
Yes, it works! Definitely matching now!

**Comment by k4yt3x** [comment] 2024-12-21 21:53
Nice. I'll see if there's anything else that needs to be changed, and I'll launch a patch 6.3.1 within today. I'll close this issue when it's merged to master branch. You can lookout for a new release in a few hours.

**Comment by Pete4K** [comment] 2024-12-21 21:58
Ok, thank you very much. I have still a question: When I use Real ESRGAN and I use a 720p File and convert it to 4K (around 6,2 FPS) it is faster than I use a 1080p  File and convert it to 4K (around 4,2 FPS). Is that normal? I would think that a 1080p File should have a faster framerate. And when I make 720p --> 2160p the file gets bigger than 1080p --> 2160p. Could that be an another bug?

**Comment by k4yt3x** [comment] 2024-12-21 22:03
What affects the speed the most for ML models it the input image size. Having a smaller input dimension will be faster to process, no matter what the output size is.

> And when I make 720p --> 2160p the file gets bigger than 1080p --> 2160p.

This is not a bug. It's handled by the encoder, not Video2X.

**Comment by Pete4K** [comment] 2024-12-21 22:09
OK

**Closed** 2024-12-21 22:21 UTC
Labels: type:Bug, state:InProgress

**Comment by k4yt3x** [comment] 2024-12-22 00:43
@Pete4K just giving you a ping. 6.3.1 is out with the patch.

**Comment by Pete4K** [comment] 2024-12-22 06:39
Thank you very much for your fast solving of the issue! I try it in a few hours.
