### ISSUE TITLE
Cannot use Anime4KCPP with Docker image.

### ISSUE THREAD

**Issue by solonovamax** [k4yt3x/video2x#388] opened 2020-10-21 20:43 UTC
## Component Versions

- **Video2X release version**:
4.6.0
- **Upscaler version**:
Anime4kCpp (N/A for version)
- **GUI version**:
N/A
- **CLI version**:
4.1.1 (?)
## Symptom

Title says it all. Anime4kCpp is not available.

## Error Log or Screenshots

```
[!] ERROR: Specified driver executable directory doesn't exist
[!] ERROR: Please check the configuration file settings
[!] ERROR: An exception has occurred
Traceback (most recent call last):
  File "/video2x/src/video2x.py", line 259, in <module>
    upscaler.run()
  File "/video2x/src/upscaler.py", line 513, in run
    self._check_arguments()
  File "/video2x/src/upscaler.py", line 223, in _check_arguments
    raise FileNotFoundError(driver_path)
FileNotFoundError: /video2x/src/dependencies/anime4kcpp/anime4kcpp
```

**Comment by k4yt3x** [comment] 2020-10-22 00:54
Duplicate of #325

**Closed by k4yt3x** 2020-10-22 00:54 UTC
Labels: duplicate

**Comment by solonovamax** [comment] 2020-10-22 00:55
Oops, forgot to check for dupes. Sorry.
