### ISSUE TITLE
Custom Resolution Support

### ISSUE THREAD

**Issue by epiccofficial** [k4yt3x/video2x#338] opened 2020-08-23 12:28 UTC
I think it would be helpful to have the option to set a custom resolution in the video2x GUI so that I can upscale my 710x480 DVD rips to 1440x1080 exactly, and I get confused on the cmd one.

Thanks!

**Comment by k4yt3x** [comment] 2020-09-01 05:55
Duplicate of #300

**Closed by k4yt3x** 2020-09-01 05:55 UTC
Labels: type:Enhancement
