### ISSUE TITLE
[V6.0.0-beta2]error while loading shared libraries: libvideo2x.so

### ISSUE THREAD

**Issue by BuyMyMojo** [k4yt3x/video2x#1180] opened 2024-10-10 09:40 UTC
While trying to run under Nobara(fedora) linux it spits out this error:
```sh
➜  video2x-linux-amd64 ./video2x 
./video2x: error while loading shared libraries: libvideo2x.so: cannot open shared object file: No such file or directory
```

by default Linux won't always try and find libraries in the same folder as the executable but during compilation you can add that ability I believe, I'm not entirely sure of the syntax myself though.

**Comment by BuyMyMojo** [comment] 2024-10-10 09:44
A quick fix is to add the path to your LD_LIBRARY_PATH before running but not ideal
```sh
export LD_LIBRARY_PATH="/home/buymymojo/Downloads/video2x-linux-amd64:$LD_LIBRARY_PATH"
```

**Comment by k4yt3x** [comment] 2024-10-10 10:17
Yeah, I did say that in the README. Ideally you'll put the .so in /usr/lib, which is what the PKGBUILD for Arch already does. For the release I'm just dumping all the files in one ZIP. I'll need to build a .deb package in the future.

**Comment by k4yt3x** [comment] 2024-10-14 04:03
I'm closing this since it's not an issue. It's the expected behavior. This will be made easier when we start building .deb packages for Debian.

**Closed by k4yt3x** 2024-10-14 04:03 UTC
