### ISSUE TITLE
ininvalid novalise or scale argument

### ISSUE THREAD

**Issue by Mirrorman95** [k4yt3x/video2x#158] opened 2019-10-24 20:40 UTC
## Environment Information

|Module|Version|
|-|-|
|`Video2X`|2.1.0|
|`FFmpeg`|ffmpeg-latest-win64-static|
|`waifu2x-caffe`||
|`waifu2x-converter-cpp`||
|`waifu2x-ncnn-vulkan`|20190712|

## Symptom

I received different error messages when trying to convert versions of the video with codecs video2x_gui.exe didn't support, so I tried it with an h264 avi, which I knew it would support, but it gave me this error message block instead. I used the NCNN Driver, the CUDNN Method (which my computer does support and have installed), 2 Threads, Scale Ratio 6 on a 320p video, and Format PNG. I checked the folder; the frames were extracted just fine, but the upscaler gets stuck on 0%.

## Screenshots or Error Messages

```
2019-10-24 15:28:49.526164 [+] INFO: Extracted frames are being saved to: C:\Users\Owner\AppData\Local\Temp\video2x\tmprw_n0z4g
2019-10-24 15:28:49.528179 [+] INFO: Upscaled frames are being saved to: C:\Users\Owner\AppData\Local\Temp\video2x\tmpcd_nbdvx
2019-10-24 15:28:49.529179 [+] INFO: Executing: ['C:\\Users\\Owner\\AppData\\Local\\video2x\\ffmpeg-latest-win64-static\\bin\\ffmpeg.exe', '-hwaccel', 'auto', '-y', '-i', 'E:\\4K Video Downloader\\Hexen\\Istart.avi', '-pix_fmt', 'rgba64be', 'C:\\Users\\Owner\\AppData\\Local\\Temp\\video2x\\tmprw_n0z4g\\extracted_%0d.PNG']
ffmpeg version git-2019-10-23-ac0f5f4 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20191010
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 35.101 / 56. 35.101
  libavcodec     58. 59.102 / 58. 59.102
  libavformat    58. 33.100 / 58. 33.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 64.100 /  7. 64.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Guessed Channel Layout for Input Stream #0.1 : mono
Input #0, avi, from 'E:\4K Video Downloader\Hexen\Istart.avi':
  Duration: 00:02:21.65, start: 0.000000, bitrate: 4028 kb/s
    Stream #0:0: Video: h264 (High 4:4:4 Predictive) (H264 / 0x34363248), gbrp(pc, gbr/unknown/unknown, progressive), 320x192 [SAR 1:1 DAR 5:3], 3947 kb/s, 15 fps, 15 tbr, 15 tbn, 30 tbc
    Stream #0:1: Audio: pcm_u8 ([1][0][0][0] / 0x0001), 11025 Hz, mono, u8, 88 kb/s
[h264 @ 000001b72043ec40] Using auto hwaccel type dxva2 with new default device.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> png (native))
Press [q] to stop, [?] for help
Output #0, image2, to 'C:\Users\Owner\AppData\Local\Temp\video2x\tmprw_n0z4g\extracted_%0d.PNG':
  Metadata:
    encoder         : Lavf58.33.100
    Stream #0:0: Video: png, rgba64be, 320x192 [SAR 1:1 DAR 5:3], q=2-31, 200 kb/s, 15 fps, 15 tbn, 15 tbc
    Metadata:
      encoder         : Lavc58.59.102 png
frame= 2125 fps=232 q=-0.0 Lsize=N/A time=00:02:21.66 bitrate=N/A dup=6 drop=0 speed=15.5x
video:70328kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[+] INFO: Reading video information
2019-10-24 15:28:58.914249 [+] INFO: Executing: C:\Users\Owner\AppData\Local\video2x\ffmpeg-latest-win64-static\bin\ffprobe.exe -v quiet -print_format json -show_format -show_streams -i E:\4K Video Downloader\Hexen\Istart.avi
2019-10-24 15:28:58.969247 [+] INFO: Executing: C:\Users\Owner\AppData\Local\video2x\ffmpeg-latest-win64-static\bin\ffprobe.exe -v quiet -pix_fmts
2019-10-24 15:28:59.013256 [+] INFO: {'yuv420p': 12, 'yuyv422': 16, 'rgb24': 24, 'bgr24': 24, 'yuv422p': 16, 'yuv444p': 24, 'yuv410p': 9, 'yuv411p': 12, 'gray': 8, 'monow': 1, 'monob': 1, 'pal8': 8, 'yuvj420p': 12, 'yuvj422p': 16, 'yuvj444p': 24, 'uyvy422': 16, 'uyyvyy411': 12, 'bgr8': 8, 'bgr4': 4, 'bgr4_byte': 4, 'rgb8': 8, 'rgb4': 4, 'rgb4_byte': 4, 'nv12': 12, 'nv21': 12, 'argb': 32, 'rgba': 32, 'abgr': 32, 'bgra': 32, 'gray16be': 16, 'gray16le': 16, 'yuv440p': 16, 'yuvj440p': 16, 'yuva420p': 20, 'rgb48be': 48, 'rgb48le': 48, 'rgb565be': 16, 'rgb565le': 16, 'rgb555be': 15, 'rgb555le': 15, 'bgr565be': 16, 'bgr565le': 16, 'bgr555be': 15, 'bgr555le': 15, 'vaapi_moco': 0, 'vaapi_idct': 0, 'vaapi_vld': 0, 'yuv420p16le': 24, 'yuv420p16be': 24, 'yuv422p16le': 32, 'yuv422p16be': 32, 'yuv444p16le': 48, 'yuv444p16be': 48, 'dxva2_vld': 0, 'rgb444le': 12, 'rgb444be': 12, 'bgr444le': 12, 'bgr444be': 12, 'ya8': 16, 'bgr48be': 48, 'bgr48le': 48, 'yuv420p9be': 13, 'yuv420p9le': 13, 'yuv420p10be': 15, 'yuv420p10le': 15, 'yuv422p10be': 20, 'yuv422p10le': 20, 'yuv444p9be': 27, 'yuv444p9le': 27, 'yuv444p10be': 30, 'yuv444p10le': 30, 'yuv422p9be': 18, 'yuv422p9le': 18, 'gbrp': 24, 'gbrp9be': 27, 'gbrp9le': 27, 'gbrp10be': 30, 'gbrp10le': 30, 'gbrp16be': 48, 'gbrp16le': 48, 'yuva422p': 24, 'yuva444p': 32, 'yuva420p9be': 22, 'yuva420p9le': 22, 'yuva422p9be': 27, 'yuva422p9le': 27, 'yuva444p9be': 36, 'yuva444p9le': 36, 'yuva420p10be': 25, 'yuva420p10le': 25, 'yuva422p10be': 30, 'yuva422p10le': 30, 'yuva444p10be': 40, 'yuva444p10le': 40, 'yuva420p16be': 40, 'yuva420p16le': 40, 'yuva422p16be': 48, 'yuva422p16le': 48, 'yuva444p16be': 64, 'yuva444p16le': 64, 'vdpau': 0, 'xyz12le': 36, 'xyz12be': 36, 'nv16': 16, 'nv20le': 20, 'nv20be': 20, 'rgba64be': 64, 'rgba64le': 64, 'bgra64be': 64, 'bgra64le': 64, 'yvyu422': 16, 'ya16be': 32, 'ya16le': 32, 'gbrap': 32, 'gbrap16be': 64, 'gbrap16le': 64, 'qsv': 0, 'mmal': 0, 'd3d11va_vld': 0, 'cuda': 0, '0rgb': 24, 'rgb0': 24, '0bgr': 24, 'bgr0': 24, 'yuv420p12be': 18, 'yuv420p12le': 18, 'yuv420p14be': 21, 'yuv420p14le': 21, 'yuv422p12be': 24, 'yuv422p12le': 24, 'yuv422p14be': 28, 'yuv422p14le': 28, 'yuv444p12be': 36, 'yuv444p12le': 36, 'yuv444p14be': 42, 'yuv444p14le': 42, 'gbrp12be': 36, 'gbrp12le': 36, 'gbrp14be': 42, 'gbrp14le': 42, 'yuvj411p': 12, 'bayer_bggr8': 8, 'bayer_rggb8': 8, 'bayer_gbrg8': 8, 'bayer_grbg8': 8, 'bayer_bggr16le': 16, 'bayer_bggr16be': 16, 'bayer_rggb16le': 16, 'bayer_rggb16be': 16, 'bayer_gbrg16le': 16, 'bayer_gbrg16be': 16, 'bayer_grbg16le': 16, 'bayer_grbg16be': 16, 'xvmc': 0, 'yuv440p10le': 20, 'yuv440p10be': 20, 'yuv440p12le': 24, 'yuv440p12be': 24, 'ayuv64le': 64, 'ayuv64be': 64, 'videotoolbox_vld': 0, 'p010le': 15, 'p010be': 15, 'gbrap12be': 48, 'gbrap12le': 48, 'gbrap10be': 40, 'gbrap10le': 40, 'mediacodec': 0, 'gray12be': 12, 'gray12le': 12, 'gray10be': 10, 'gray10le': 10, 'p016le': 24, 'p016be': 24, 'd3d11': 0, 'gray9be': 9, 'gray9le': 9, 'gbrpf32be': 96, 'gbrpf32le': 96, 'gbrapf32be': 128, 'gbrapf32le': 128, 'drm_prime': 0, 'opencl': 0, 'gray14be': 14, 'gray14le': 14, 'grayf32be': 32, 'grayf32le': 32, 'yuva422p12be': 36, 'yuva422p12le': 36, 'yuva444p12be': 48, 'yuva444p12le': 48, 'nv24': 24, 'nv42': 24}
[+] INFO: Framerate: 15.001500150015001
[+] INFO: Starting to upscale extracted images
2019-10-24 15:29:00.581248 [+] INFO: Starting upscaled image cleaner
2019-10-24 15:29:00.583252 [+] INFO: [upscaler] Thread 1 started
2019-10-24 15:29:00.583252 [+] INFO: [upscaler] Thread 0 started
2019-10-24 15:29:00.584247 [+] INFO: Executing: ['C:\\Users\\Owner\\AppData\\Local\\video2x\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan.exe', '-i', 'C:\\Users\\Owner\\AppData\\Local\\Temp\\video2x\\tmprw_n0z4g\\1', '-o', 'C:\\Users\\Owner\\AppData\\Local\\Temp\\video2x\\tmpcd_nbdvx', '-n', '2', '-s', '6.0', '-t', '400', '-m', 'models-cunet', '-g', '0', '-j', '1:2:2']2019-10-24 15:29:00.585251 [+] INFO: Executing: ['C:\\Users\\Owner\\AppData\\Local\\video2x\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan.exe', '-i', 'C:\\Users\\Owner\\AppData\\Local\\Temp\\video2x\\tmprw_n0z4g\\0', '-o', 'C:\\Users\\Owner\\AppData\\Local\\Temp\\video2x\\tmpcd_nbdvx', '-n', '2', '-s', '6.0', '-t', '400', '-m', 'models-cunet', '-g', '0', '-j', '1:2:2']

ininvalid novalise or scale argument
Upscaling Progress:   0%|                                                                     | 0/2125 [00:00<?, ?it/s]d noise or scale argument
2019-10-24 15:29:00.613252 [+] INFO: Killing upscaled image cleaner
Upscaling Progress:   0%|                                                                     | 0/2125 [00:01<?, ?it/s]Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "video2x_gui.py", line 321, in _upscale
  File "upscaler.py", line 357, in run
  File "upscaler.py", line 293, in _upscale_frames
  File "waifu2x_ncnn_vulkan.py", line 83, in upscale
  File "subprocess.py", line 487, in run
subprocess.CalledProcessError: Command '['C:\\Users\\Owner\\AppData\\Local\\video2x\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan.exe', '-i', 'C:\\Users\\Owner\\AppData\\Local\\Temp\\video2x\\tmprw_n0z4g\\1', '-o', 'C:\\Users\\Owner\\AppData\\Local\\Temp\\video2x\\tmpcd_nbdvx', '-n', '2', '-s', '6.0', '-t', '400', '-m', 'models-cunet', '-g', '0', '-j', '1:2:2']' returned non-zero exit status 4294967295.

Upscaling Progress:   0%|                                                                     | 0/2125 [00:02<?, ?it/s]
```

**Comment by k4yt3x** [comment] 2019-10-24 23:19
I think this is where the problem is located:

![image](https://user-images.githubusercontent.com/21986859/67532098-88223480-f6b4-11e9-81cd-96db51f81268.png)

Changing the scaling ratio arg to integer should solve the problem. However, since you're using the released EXE version, you won't be able to just edit it and get it to work.

I'll release a patch for 2.X.X tonight, and it will also be fixed in 3.0.0.

**Comment by k4yt3x** [comment] 2019-10-25 01:44
I just updated the release ZIP. Try the new one.

**Closed by k4yt3x** 2019-10-25 01:44 UTC
Labels: bug

**Comment by Mirrorman95** [comment] 2019-10-25 08:44
The error message I get is very similar, but diverges when it starts trying to upscale the image:
```
2019-10-25 03:37:37.964943 [+] INFO: Starting upscaled image cleaner
2019-10-25 03:37:37.966943 [+] INFO: [upscaler] Thread 1 started
2019-10-25 03:37:37.966943 [+] INFO: [upscaler] Thread 0 started2019-10-25 03:37:37.967943 [+] INFO: Executing: ['C:\\Users\\Owner\\AppData\\Local\\video2x\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan.exe', '-i', 'C:\\Users\\Owner\\AppData\\Local\\Temp\\video2x\\tmpotsxt0sv\\1', '-o', 'C:\\Users\\Owner\\AppData\\Local\\Temp\\video2x\\tmpl2ruamtd', '-n', '2', '-s', '6', '-t', '400', '-m', 'models-cunet', '-g', '0', '-j', '1:2:2']

2019-10-25 03:37:37.972944 [+] INFO: Executing: ['C:\\Users\\Owner\\AppData\\Local\\video2x\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan.exe', '-i', 'C:\\Users\\Owner\\AppData\\Local\\Temp\\video2x\\tmpotsxt0sv\\0', '-o', 'C:\\Users\\Owner\\AppData\\Local\\Temp\\video2x\\tmpl2ruamtd', '-n', '2', '-s', '6', '-t', '400', '-m', 'models-cunet', '-g', '0', '-j', '1:2:2']
Upscaling Progress:   0%|                                                                     | 0/2125 [00:00<?, ?it/s]invalid noise or scale argument
e or scale argument
2019-10-25 03:37:37.989944 [+] INFO: Killing upscaled image cleaner
Upscaling Progress:   0%|                                                                     | 0/2125 [00:01<?, ?it/s]Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "video2x_gui.py", line 321, in _upscale
  File "upscaler.py", line 357, in run
  File "upscaler.py", line 293, in _upscale_frames
  File "waifu2x_ncnn_vulkan.py", line 83, in upscale
  File "subprocess.py", line 487, in run
subprocess.CalledProcessError: Command '['C:\\Users\\Owner\\AppData\\Local\\video2x\\waifu2x-ncnn-vulkan\\waifu2x-ncnn-vulkan.exe', '-i', 'C:\\Users\\Owner\\AppData\\Local\\Temp\\video2x\\tmpotsxt0sv\\1', '-o', 'C:\\Users\\Owner\\AppData\\Local\\Temp\\video2x\\tmpl2ruamtd', '-n', '2', '-s', '6', '-t', '400', '-m', 'models-cunet', '-g', '0', '-j', '1:2:2']' returned non-zero exit status 4294967295.

Upscaling Progress:   0%|                                                                     | 0/2125 [00:02<?, ?it/s]
```

**Comment by k4yt3x** [comment] 2019-10-25 20:55
Does the problem persist with one thread?
Using multiple threads of waifu2x doesn't help all that much.

**Comment by Mirrorman95** [comment] 2019-10-26 05:53
Well, when I ran Waifu2x-Caffe yesterday and it worked, I was only using one thread, so that could be it. But when I did, the progress bar stopped updating after 2%. Then it upscaled the rest of the frames without updating the % or making them into a video.

**Comment by k4yt3x** [comment] 2019-10-26 17:41
That's strange. Here's a typical situation of "it works on my machine".

I don't even know how to debug it right now.
The only solution I have at the moment is to go through the source code again and see if I did something improperly.
