### ISSUE TITLE
Unable to execute video2x.py

### ISSUE THREAD

**Issue by maniac236** [k4yt3x/video2x#106] opened 2019-06-16 13:06 UTC
When trying to execute video2x.py, a syntax error shows up.

C:\Users\PC-ADMIN\Desktop\upscalers\video2x-master\bin>python video2x.py -m gpu -r 4 -i C:\Users\PC-ADMIN\Desktop\1.mp4 -o C:\Users\PC-ADMIN\Desktop\2.mp4
  File "video2x.py", line 4
    __      __  _       _                  ___   __   __
             ^
SyntaxError: invalid syntax

I'm kinda of a noob but, from what I understand, Python is trying to execute one of the string lines (the one forming the superior part of the video2x title) and I just have no idea of why it does this. Sorry for the inconvenience.

**Comment by k4yt3x** [comment] 2019-06-16 18:25
That's interesting. @BrianPetkovsek just updated the repo so it's backwards compatible with older versions of Python (#104), so this might have something to do with the update.

Try running the setup script and see if that fixes the problem.

**Comment by AmazingPenis** [comment] 2019-06-16 19:31
Ok, I will look into it. I'm op btw, had to change accounts.

**Comment by BrianPetkovsek** [comment] 2019-06-16 20:18
huh i tested multiple times to see if everything still works.
i'll look into it

**Comment by BrianPetkovsek** [comment] 2019-06-16 21:39
should be fixed now

**Comment by BrianPetkovsek** [comment] 2019-06-16 21:39
should be fixed now @AmazingPenis @maniac236

**Comment by k4yt3x** [comment] 2019-06-17 11:52
I'm unable to reproduce this problem.
@BrianPetkovsek did you manage to reproduce it before PR #107?

**Comment by AmazingPenis** [comment] 2019-06-17 12:30
Keeps happening. This is pretty weird since I can run dandere just fine.

**Comment by BrianPetkovsek** [comment] 2019-06-17 16:09
@AmazingPenis can you try the pull request that might fix the problem [here](https://github.com/BrianPetkovsek/video2x/tree/Fix-encoding-problem)
After downloading the files could you run the **video2x_setup.py** script.
then run video2x.

**Comment by BrianPetkovsek** [comment] 2019-06-17 16:19
@k4yt3x it looks like it might be an issue on the chunking future-fstrings uses. chucks halfway through the video2x title and errors because of it. 
I was able to reproduce the bug. Simply remove the two newlines from the coding line and the video2x title. 
![screenshot](https://i.imgur.com/bd12JJM.png)

make sure future-fstrings is up to date by uninstall and reinstalling it.

**Comment by AmazingPenis** [comment] 2019-06-17 20:12
Yep, now it works. Thank you a lot.

**Comment by k4yt3x** [comment] 2019-06-18 15:32
This should now be fixed with PR #107.

**Closed by k4yt3x** 2019-06-18 15:32 UTC
Labels: bug
