### ISSUE TITLE
Reuse already extracted frames

### ISSUE THREAD

**Issue by rebb** [k4yt3x/video2x#483] opened 2021-03-19 18:24 UTC
## Description

Re-Use extracted frames to avoid having to extract them each time Video2X is run. This would help with tweaking settings, without having to wait for the extraction each time.

## Sources

Paste links to descriptions of related documentations, websites and etc. here.

**Comment by k4yt3x** [comment] 2021-03-22 11:05
Duplicate of #245

**Closed by k4yt3x** 2021-03-22 11:05 UTC
