### ISSUE TITLE
Implement a Resume function

### ISSUE THREAD

**Issue by Felixkruemel** [k4yt3x/video2x#264] opened 2020-05-22 14:23 UTC
I would like to see a resume function.

Since Video2x just upscales single pictures and save the upscaled ones next to the original ones in a set temp folder it should be easy to search on startup (or with a dedicated button) wether a upscaling project can be resumed or not. The user would just need to enter the original file again for the Audio stream (if I understood that correctly) and the process could continue where it crashed or has been stopped.

**Comment by k4yt3x** [comment] 2020-05-22 14:27
Duplicate of #65

**Comment by skerit** [comment] 2020-05-27 15:51
@k4yt3x Issue #65 seems to be going the way of "pausing" a running process and resuming the same process later. This "resume" is more like a "crash recovery". (I would love that, because the vulkan stuff on my Linux box seems to randomly stop working after a while, when I'm 85% done)

**Comment by k4yt3x** [comment] 2020-05-27 21:17
@skerit ok fair enough, I'll reopen this issue then.
Pause&continue will require some time to implement, but maybe this can be done before that.

**Comment by GabenCrying** [comment] 2021-09-28 23:29
Le Lost Power 6 Days In To Conversion Face

**Comment by k4yt3x** [comment] 2022-02-10 05:50
I'll close this since it's a duplicate of #65. Let's move all future discussions there.

**Closed by k4yt3x** 2022-02-10 05:50 UTC
Labels: type:Enhancement
