### ISSUE TITLE
[Error] An Exception Has Occurred 

### ISSUE THREAD

**Issue by SupremMotu** [k4yt3x/video2x#67] opened 2019-03-30 02:12 UTC
https://imgur.com/a/BL3MRD6

I don't know what is going on. Before this error, I got missing MSVCP140.dll and Concrt140.dll missing, but I downloaded them from DLL-files.com. Did I do something wrong?

**Comment by K4YT3X** [comment] 2019-03-30 18:16
I'm not sure what the problem is. The error messages printed by waifu2x cannot be displayed due to its Japanese encoding. Could you please change the code page before running the program?

**Comment by SupremMotu** [comment] 2019-03-31 02:50
How would I change the code page?

**Comment by k4yt3x** [comment] 2019-03-31 19:56
`chcp 65001`

**Comment by BrianPetkovsek** [comment] 2019-04-03 04:50
> https://imgur.com/a/BL3MRD6
> 
> I don't know what is going on. Before this error, I got missing MSVCP140.dll and Concrt140.dll missing, but I downloaded them from DLL-files.com. Did I do something wrong?

MSVCP140.dll and Concrt140.dll is a part of the Microsoft Redistributable Package.
You can download and install the official redistributable package here.
https://www.microsoft.com/en-us/download/details.aspx?id=48145

Im also recommending deleting the files downloaded from DLL-files.com and run a malware scan. as any unofficial dll probably has viruses.
A good malware scanning software is: https://www.malwarebytes.com/
or any antivirus software would work as well.

**Comment by SupremMotu** [comment] 2019-04-03 05:43
Thanks, I just made a new VM, downloaded Microsoft C++ Redistributable, and it worked liked a charm. Thanks for the help.

**Comment by cikeZ00** [comment] 2019-04-04 01:05
Got the same error.
Selecting the error text and copying it gives me this:

変変換換にに失失敗敗ししたたフファァイイルルががあありりまますす

**Comment by k4yt3x** [comment] 2019-04-06 14:22
> Thanks, I just made a new VM, downloaded Microsoft C++ Redistributable, and it worked liked a charm. Thanks for the help.

If it's solved then I'm closing this issue.

**Comment by k4yt3x** [comment] 2019-04-06 14:22
@cikeZ00 if you're getting the same error as him, maybe the same fix would work for you.

**Closed by k4yt3x** 2019-04-06 14:22 UTC
Labels: help wanted, question

**Comment by cikeZ00** [comment] 2019-04-08 12:37
@k4yt3x upon a closer look the errors between me and him seem to be different.

Since i don't know exactly what error he has I looked through the screenshot and the arrangement of the symbols are different to mine.

I don't know if I understood the error correctly since im still new to Japanese but it seems as tho it can't find the images it stored in the temp folder

**Comment by k4yt3x** [comment] 2019-04-08 13:13
@cikeZ00  If you're unsure whether you'll be able to solve the issue or not, just open a new issue and provide the details and I'll take a look.
