### ISSUE TITLE
ffmpeg issue

### ISSUE THREAD

**Issue by meguerreroa** [K4YT3X/video2x#34] opened 2019-01-24 11:56 UTC
While ffmpeg was woking extracting the audio, it returned this error
![image](https://user-images.githubusercontent.com/36995005/51676242-0e81dc80-1fa4-11e9-9393-71073c33d94e.png)
Creating an empty output_audio.aac
So when it was copying that audio on the final video:
![image](https://user-images.githubusercontent.com/36995005/51676378-73d5cd80-1fa4-11e9-807b-7b0a1a5e6b9c.png)

I repeated the process inserting the commands on my own and got it working using -acodec aac 
I was working with a .avi video. It is a problem with that video format? Or a common error? I used ffmpeg 4.1 

Thanks for your awesome work

**Comment by K4YT3X** [comment] 2019-01-24 21:32
> Thanks for your awesome work

Thank you :P

Could you please send me the original command and what you added? That will help me locating the problem. I'm still struggling whether to use the python ffmpeg library or continue down the current path.

**Comment by K4YT3X** [comment] 2019-01-24 21:38
I have the current `-acodec` set to `copy`, so the codec should work. Did ffmpeg misdetect the codec or something?

**Comment by meguerreroa** [comment] 2019-01-25 01:31
As you said, the original command was -acodec copy, maybe it was a kind of unusual bug. I'll download again ffmpeg and i'll test again.

**Comment by K4YT3X** [comment] 2019-01-25 13:51
Ok. Tell me if the problem persists. If the issue remains, it's the best if I can have the original video for debugging.

**Comment by meguerreroa** [comment] 2019-01-28 15:11
Sorry for the late reply. Here's the video if you want to test
https://mega.nz/#!D5xACICZ!u80qVS4H58EW6EbXRBa3gNdMf1H6-TWyq-ul2JdXwdo
I haven't tested with another video yet, i'll post the result when i do

**Comment by K4YT3X** [comment] 2019-01-31 02:39
@meguerreroa ok I see what's going on.

Basically in the following command, ffmpeg is trying to extract whatever format the audio is into AAC without converting the codec. If the audio already is AAC, then there's no problem. However, in your case, the audio stream is in MP3 format. Therefore, ffmpeg tries to extract MP3 into AAC without converting, which doesn't work.

```
ffmpeg -i c:\something\op05.avi -vn -acodec copy c:\something\output-audio.aac -y
```

I think what I have to do is to specify the extracted audio's format, which is to do what you did -- changing `-acodec copy` into `-acodec aac`. However, I'm not sure if that's going to cause any other problems. I'll try this pending solution with some other videos and check if the patch is stable.

Also, if you want, I have your video upscaled. I can share it with you so you don't need to run it again.

**Comment by meguerreroa** [comment] 2019-01-31 03:40
Wow, thanks, now I understand what was wrong. I hope that this question will be useful for you to find a suitable solution. Also thanks for upscaling the video.

**Comment by K4YT3X** [comment] 2019-01-31 03:54
@meguerreroa much obliged. Thanks for providing the original video so I was able to locate the problem. I'll close this issue once the problem is confirmed to be eliminated.

**Closed** 2019-02-07 16:12 UTC
Labels: bug
