### ISSUE TITLE
Video Full of Artifacts

### ISSUE THREAD

**Issue by HenDGS** [k4yt3x/video2x#297] opened 2020-06-10 18:10 UTC
So I upscaled a video using v4.5.0, first with anime4kcpp and after with waifu2x-ncnn-vulkan. I thought it was anime4k's fault that the video had a lot of artifacts, but the same thing happened waifu2x-ncnn-vulkan. 

These are some prints that I took so you can have an example: https://imgur.com/a/QeVk5Vr

Here is my base video mediainfo: 
[a.txt](https://github.com/k4yt3x/video2x/files/4760375/a.txt)

And here is the output mediainfo:
[a_output.txt](https://github.com/k4yt3x/video2x/files/4760377/a_output.txt)

**Comment by k4yt3x** [comment] 2020-06-11 02:37
Hmmm interesting. This kind of issues usually isn't Video2X's problem, so I'm guessing it might be your video player.
Does the same issue exist on VLC?

**Comment by k4yt3x** [comment] 2020-06-11 02:38
Also try 4.6.0

**Comment by xXHenlolXx** [comment] 2020-06-11 02:42
Sorry, it was actually 4.6.0. And the issue continues while playing the video on other players. I tested mpv, MPC-HC, Movies and TV and Windows Media Player.

**Comment by xXHenlolXx** [comment] 2020-06-11 02:46
I tried anime4k with v4.5.0. I even mentioned the artifacts on the other post, but I thought it was anime4k's problem.

> Standard waifu2x and anime4k are working - but anime4k had a lot of artifacts.

**Comment by k4yt3x** [comment] 2020-06-11 03:54
Could you please send me the original video?
I'll test it out in my environment and see what's wrong.

**Comment by TianZerL** [comment] 2020-06-11 07:27
looks like encoding or decoding problem，maybe try another encoder or decoder of ffmpeg.

**Comment by xXHenlolXx** [comment] 2020-06-12 16:10
> Could you please send me the original video?
> I'll test it out in my environment and see what's wrong.

Here is it: https://drive.google.com/file/d/1YTW2moO1u_cgZKkiq51gTjJK-jZ-Td4v/view?usp=sharing

**Comment by xXHenlolXx** [comment] 2020-06-23 23:03
@k4yt3x Are you alive?

**Comment by k4yt3x** [comment] 2020-06-23 23:05
Yes I am, I've been unable to reproduce the problems and I'm hung up on something else right now.

**Comment by xXHenlolXx** [comment] 2020-06-24 00:00
No problem, I just found weird that you were not responding, but I should have checked your twitter or gitmemory before. "I've been unable to reproduce the problems" About this, I can try to upscale the same video again, to see if it will happen.

**Comment by xXHenlolXx** [comment] 2020-06-26 19:53
![mpv-shot0001](https://user-images.githubusercontent.com/27168630/85895707-8ec9f400-b7cd-11ea-8f25-ae9cc13f52fd.jpg)
Same result

**Comment by k4yt3x** [comment] 2020-06-27 00:18
Feels more like a decoding problem.

**Comment by xXHenlolXx** [comment] 2020-06-27 00:23
Do you have any idea how to solve it?

**Comment by k4yt3x** [comment] 2020-06-28 11:25
Actually, could you please send me the output video?
I'll take a look at what's wrong with it.

**Comment by nebekerb** [comment] 2021-11-19 23:02
Was a solution found? I am running into artifacts as well.

**Comment by k4yt3x** [comment] 2021-11-21 00:37
Well the first thing I'd suggest you to try is to use software decoding. Some players have problems hardware-decode large video files and produce artifacts.

**Comment by nebekerb** [comment] 2021-11-22 16:42
> Well the first thing I'd suggest you to try is to use software decoding. Some players have problems hardware-decode large video files and produce artifacts.

Thank you! Wow, after upscaling for 152 hours I feared the results were a loss. You are a hero!!

**Comment by k4yt3x** [comment] 2021-11-25 05:48
I think this might be the solution for the initial post too. I'm closing it for now. Feel free to comment and reopen.

**Closed by k4yt3x** 2021-11-25 05:48 UTC
Labels: type:Bug

**Comment by FelixRobotics** [comment] 2023-02-20 07:43
i'm running into artifacts as well, how do i use software encoding/decoding?  this software is fantastic btw (all except for the artifacts ofc) and i know how hard it is to create things, can't imagine creating something that creates other things

here's a link to all the versions i've tested: https://www.mediafire.com/file/7cetuvdb64dffvy/video2x.zip/file
